/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GitHubImageUploader
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  repo: "",
  branch: "main",
  pathTemplate: "images/{year}/{month}",
  filenameTemplate: "{year}{month}{day}-{timestamp}-{rand}.{ext}",
  token: "",
  customDomain: "",
  urlMode: "custom"
};
var GitHubImageUploader = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new GitHubImageUploaderSettingTab(this.app, this));
    this.addCommand({
      id: "upload-image-to-github",
      name: "Upload image to GitHub",
      editorCallback: (editor) => {
        this.openFilePicker(editor);
      }
    });
    this.registerEvent(
      this.app.workspace.on(
        "editor-paste",
        (evt, editor) => {
          this.handlePaste(evt, editor);
        }
      )
    );
    this.registerEvent(
      this.app.workspace.on(
        "editor-drop",
        (evt, editor) => {
          this.handleDrop(evt, editor);
        }
      )
    );
    this.addCommand({
      id: "convert-links-custom-domain-current",
      name: "Convert image links to custom domain (current note)",
      editorCallback: () => {
        this.convertLinks(false);
      }
    });
    this.addCommand({
      id: "convert-links-custom-domain-vault",
      name: "Convert image links to custom domain (whole vault)",
      callback: () => {
        this.convertLinks(true);
      }
    });
    this.addCommand({
      id: "refresh-images-current-note",
      name: "Refresh images in current note",
      editorCallback: (editor) => {
        this.refreshImages();
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ---------- Event handlers ----------
  async handlePaste(evt, editor) {
    var _a;
    const files = (_a = evt.clipboardData) == null ? void 0 : _a.files;
    if (!files || files.length === 0) return;
    const images = Array.from(files).filter((f) => f.type.startsWith("image/"));
    if (images.length === 0) return;
    evt.preventDefault();
    for (const file of images) {
      await this.uploadAndInsert(file, editor);
    }
  }
  async handleDrop(evt, editor) {
    var _a;
    const files = (_a = evt.dataTransfer) == null ? void 0 : _a.files;
    if (!files || files.length === 0) return;
    const images = Array.from(files).filter((f) => f.type.startsWith("image/"));
    if (images.length === 0) return;
    evt.preventDefault();
    for (const file of images) {
      await this.uploadAndInsert(file, editor);
    }
  }
  openFilePicker(editor) {
    const input = document.createElement("input");
    input.type = "file";
    input.accept = "image/*";
    input.multiple = true;
    input.onchange = async () => {
      if (!input.files) return;
      for (const file of Array.from(input.files)) {
        await this.uploadAndInsert(file, editor);
      }
    };
    input.click();
  }
  // ---------- Core upload ----------
  async uploadAndInsert(file, editor) {
    if (!this.settings.repo || !this.settings.token) {
      new import_obsidian.Notice(
        "GitHub Image Uploader: please set the repository and token in settings first."
      );
      return;
    }
    try {
      new import_obsidian.Notice(`Uploading ${file.name} to GitHub...`);
      const base64 = await fileToBase64(file);
      const date = /* @__PURE__ */ new Date();
      const path = sanitizePath(fillDateTemplates(this.settings.pathTemplate, date));
      const filename = buildFilename(
        this.settings.filenameTemplate,
        file.name,
        date
      );
      await uploadToGitHub(this.settings, path, filename, base64);
      const url = buildInsertUrl(
        this.settings,
        path,
        filename,
        this.settings.branch
      );
      const alt = file.name.replace(/\.[^.]+$/, "") || "image";
      editor.replaceSelection(`![${alt}](${url})
`);
      new import_obsidian.Notice(`Uploaded ${filename} successfully.`);
    } catch (e) {
      console.error(e);
      const msg = e instanceof Error ? e.message : String(e);
      new import_obsidian.Notice(`GitHub Image Uploader: upload failed - ${msg}`);
    }
  }
  /**
   * Rewrite raw.githubusercontent.com / jsDelivr links for THIS repo into the
   * custom domain URL, in the current note or the whole vault. Run this after
   * Cloudflare/GitHub Pages has finished deploying.
   */
  async convertLinks(allNotes) {
    const domain = this.settings.customDomain.trim().replace(/\/+$/, "");
    if (!domain) {
      new import_obsidian.Notice(
        "GitHub Image Uploader: set a custom domain first, then convert."
      );
      return;
    }
    const active = this.app.workspace.getActiveFile();
    const files = allNotes ? this.app.vault.getMarkdownFiles() : active ? [active] : [];
    if (files.length === 0) {
      new import_obsidian.Notice("GitHub Image Uploader: no markdown file to convert.");
      return;
    }
    let count = 0;
    for (const file of files) {
      const content = await this.app.vault.read(file);
      let changed = false;
      const newContent = content.replace(
        /(!\[[^\]]*\]\()((?:https?:\/\/)[^)\s]+)(\))/g,
        (m, pre, url, post) => {
          const rel = extractRepoRel(url, this.settings);
          if (!rel) return m;
          changed = true;
          count++;
          return `${pre}${domain}/${rel}${post}`;
        }
      );
      if (changed) {
        await this.app.vault.modify(file, newContent);
      }
    }
    new import_obsidian.Notice(
      `GitHub Image Uploader: converted ${count} image link(s) to custom domain.`
    );
  }
  /**
   * Force the active note's preview to re-render so freshly-deployed
   * (previously 404) custom-domain images get fetched.
   */
  refreshImages() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      new import_obsidian.Notice(
        "GitHub Image Uploader: open the note in preview/reading mode first."
      );
      return;
    }
    view.previewMode.rerender(true);
    new import_obsidian.Notice("GitHub Image Uploader: re-rendering note images.");
  }
};
function fillDateTemplates(template, date) {
  const year = date.getFullYear().toString();
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const day = date.getDate().toString().padStart(2, "0");
  const hour = date.getHours().toString().padStart(2, "0");
  const minute = date.getMinutes().toString().padStart(2, "0");
  const second = date.getSeconds().toString().padStart(2, "0");
  return template.replace(/\{year\}/g, year).replace(/\{month\}/g, month).replace(/\{day\}/g, day).replace(/\{hour\}/g, hour).replace(/\{minute\}/g, minute).replace(/\{second\}/g, second);
}
function sanitize(seg) {
  return seg.trim().replace(/\s+/g, "-").replace(/[\\?*:"<>|]/g, "").replace(/\/+/g, "-");
}
function sanitizePath(p) {
  return p.split("/").map((seg) => sanitize(seg)).filter((s) => s.length > 0).join("/");
}
function buildFilename(template, originalName, date) {
  const dotIdx = originalName.lastIndexOf(".");
  const ext = dotIdx > 0 ? originalName.slice(dotIdx + 1) : "";
  const name = dotIdx > 0 ? originalName.slice(0, dotIdx) : originalName;
  const rand = Math.random().toString(36).slice(2, 8);
  const ts = Date.now().toString();
  return fillDateTemplates(template, date).replace(/\{timestamp\}/g, ts).replace(/\{rand\}/g, rand).replace(/\{name\}/g, sanitize(name)).replace(/\{ext\}/g, ext);
}
function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result;
      const idx = result.indexOf(",");
      resolve(idx >= 0 ? result.slice(idx + 1) : result);
    };
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(file);
  });
}
async function uploadToGitHub(settings, path, filename, content) {
  const fullPath = `${path}/${filename}`.split("/").map(encodeURIComponent).join("/");
  const apiUrl = `https://api.github.com/repos/${settings.repo}/contents/${fullPath}`;
  const res = await (0, import_obsidian.requestUrl)({
    url: apiUrl,
    method: "PUT",
    headers: {
      Authorization: `Bearer ${settings.token}`,
      "Content-Type": "application/json",
      "User-Agent": "obsidian-github-image-uploader"
    },
    body: JSON.stringify({
      message: `Upload image ${filename}`,
      content,
      branch: settings.branch
    })
  });
  if (res.status >= 400) {
    let msg = `HTTP ${res.status}`;
    try {
      if (res.json && res.json.message) msg = res.json.message;
    } catch (e) {
    }
    throw new Error(msg);
  }
}
function buildInsertUrl(settings, path, filename, branch) {
  const rel = path ? `${path}/${filename}` : filename;
  const domain = settings.customDomain.trim().replace(/\/+$/, "");
  switch (settings.urlMode) {
    case "raw":
      return `https://raw.githubusercontent.com/${settings.repo}/${branch}/${rel}`;
    case "jsdelivr":
      return `https://cdn.jsdelivr.net/gh/${settings.repo}@${branch}/${rel}`;
    case "custom":
    default:
      if (domain) return `${domain}/${rel}`;
      return `https://raw.githubusercontent.com/${settings.repo}/${branch}/${rel}`;
  }
}
function extractRepoRel(url, settings) {
  const repo = settings.repo;
  const rawPrefix = `https://raw.githubusercontent.com/${repo}/`;
  if (url.startsWith(rawPrefix)) {
    const rest = url.slice(rawPrefix.length);
    const slash = rest.indexOf("/");
    return slash === -1 ? null : rest.slice(slash + 1);
  }
  const jdPrefix = `https://cdn.jsdelivr.net/gh/${repo}@`;
  if (url.startsWith(jdPrefix)) {
    const rest = url.slice(jdPrefix.length);
    const slash = rest.indexOf("/");
    return slash === -1 ? null : rest.slice(slash + 1);
  }
  return null;
}
var GitHubImageUploaderSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    __publicField(this, "plugin");
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "GitHub Image Uploader" });
    new import_obsidian.Setting(containerEl).setName("Repository").setDesc("GitHub repository in the form `owner/repo`.").addText(
      (t) => t.setPlaceholder("owner/repo").setValue(this.plugin.settings.repo).onChange(async (v) => {
        this.plugin.settings.repo = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Branch").setDesc("Branch the images are committed to.").addText(
      (t) => t.setPlaceholder("main").setValue(this.plugin.settings.branch).onChange(async (v) => {
        this.plugin.settings.branch = v.trim() || "main";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Path template").setDesc(
      "Folder path inside the repo. Supports {year}, {month}, {day}, {hour}, {minute}, {second}. Example: images/{year}/{month}"
    ).addText(
      (t) => t.setPlaceholder("images/{year}/{month}").setValue(this.plugin.settings.pathTemplate).onChange(async (v) => {
        this.plugin.settings.pathTemplate = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Filename template").setDesc(
      "Supports {year},{month},{day},{hour},{minute},{second},{timestamp},{rand},{name},{ext}. A random suffix avoids collisions."
    ).addText(
      (t) => t.setPlaceholder("{year}{month}{day}-{timestamp}-{rand}.{ext}").setValue(this.plugin.settings.filenameTemplate).onChange(async (v) => {
        this.plugin.settings.filenameTemplate = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("GitHub Token").setDesc(
      "Personal access token with `repo` scope. Stored locally in the plugin data (plaintext)."
    ).addText((t) => {
      t.inputEl.type = "password";
      t.setPlaceholder("ghp_...").setValue(this.plugin.settings.token).onChange(async (v) => {
        this.plugin.settings.token = v.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Custom domain (optional)").setDesc(
      "Custom domain for GitHub Pages / Cloudflare Pages, e.g. https://img.example.com . Used by URL mode 'custom' and by 'Convert to custom domain'."
    ).addText(
      (t) => t.setPlaceholder("https://img.example.com").setValue(this.plugin.settings.customDomain).onChange(async (v) => {
        this.plugin.settings.customDomain = v.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("URL mode (inserted link)").setDesc(
      "'Custom domain' = your Cloudflare/GitHub Pages URL (needs the site deployed; for PRIVATE repos this is the only option that works publicly). 'GitHub raw' / 'jsDelivr' are instant but REQUIRE A PUBLIC repo and will NOT load for private repos. After deploy, run 'Refresh images in current note' to fetch them."
    ).addDropdown(
      (d) => d.addOption("raw", "GitHub raw (instant)").addOption("custom", "Custom domain (after deploy)").addOption("jsdelivr", "jsDelivr CDN").setValue(this.plugin.settings.urlMode).onChange(async (v) => {
        this.plugin.settings.urlMode = v;
        await this.plugin.saveSettings();
      })
    );
  }
};
